label: "VI-Sensor Sim"
cameras:
- camera:
    label: cam0
    image_height: 480
    image_width: 752
    type: pinhole
    intrinsics:
      cols: 1
      rows: 4
      data: [458.654, 457.296, 367.215, 248.375]
    distortion:
      type: radial-tangential
      parameters:
        cols: 1
        rows: 4 
        data: [0.0, 0.0, 0.0, 0.0]
  T_B_C:
    cols: 4
    rows: 4
    data: [1.0, 0.0, 0.0, 0.0,
           0.0, 1.0, 0.0, 0.0,
           0.0, 0.0, 1.0, 0.0,
           0.0, 0.0, 0.0, 1.0]
